// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace ProcessorModel
{
    public partial class ProcessorModel
    {
        /// <summary>
        /// model input class for ProcessorModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"Производитель")]
            public string Производитель { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"Серия")]
            public string Серия { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Поколение")]
            public float Поколение { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Модель")]
            public string Модель { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Количество ядер")]
            public float Количество_ядер { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"Количество потоков")]
            public float Количество_потоков { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"Тактовая частота ядер")]
            public float Тактовая_частота_ядер { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"Производительность")]
            public float Производительность { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for ProcessorModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Производитель")]
            public float[] Производитель { get; set; }

            [ColumnName(@"Серия")]
            public float[] Серия { get; set; }

            [ColumnName(@"Поколение")]
            public float Поколение { get; set; }

            [ColumnName(@"Модель")]
            public float[] Модель { get; set; }

            [ColumnName(@"Количество ядер")]
            public float Количество_ядер { get; set; }

            [ColumnName(@"Количество потоков")]
            public float Количество_потоков { get; set; }

            [ColumnName(@"Тактовая частота ядер")]
            public float Тактовая_частота_ядер { get; set; }

            [ColumnName(@"Производительность")]
            public float Производительность { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("ProcessorModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
